### ISSUE TITLE
[daily] Crashes with a spam of warnings

### ISSUE THREAD

**Issue by lainsce** [elementary/switchboard-plug-applications#119]
The output in Terminal is as follows:

```bash
** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10350): WARNING **: 11:35:40.055: App.vala:200: Key file does not have key “features” in group “Context”
```

Seems that method that line in `App.vala` is in, needs some help?

**Comment by danrabbit** [comment]
I can't confirm this. Can you provide some more information? Are you running on 6.x daily or 5.x daily? Do you have any flatpak apps installed? It looks like these are only warnings, can you provide more output or a backtrace?

**Comment by lainsce** [comment]
I am on 6.x daily

And I have Telegram, Slack, Discord, GIMP, Inkscape, Steam as flatpaks installed.

A `bt` run on GDB does this:
An error;
```sh
** (io.elementary.switchboard:9161): CRITICAL **: 15:09:37.476: AppManager.vala:63: Unable to get installed flatpaks: Error opening directory '/home/lains/.local/share/flatpak/app/com.discordapp.Discord': Too many open files
```

and lots of this:

```sh
#929 0x00007ffff7c5126c in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#930 0x00007ffff7c53378 in g_object_new_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#931 0x00007ffff7c536cd in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#932 0x00007fffd7a89532 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#933 0x00007ffff7e9a0eb in g_ptr_array_foreach ()

```

**Comment by danrabbit** [comment]
It would be really helpful if you could provide complete logs please

**Comment by lainsce** [comment]
That's basically the complete log, it just does this error, the warnings of the original issue post, and then a lot of the same second snippet, see how it goes up to #933?

It'd do it like this:
```bash
** (io.elementary.switchboard:9161): CRITICAL **: 15:09:37.476: AppManager.vala:63: Unable to get installed flatpaks: Error opening directory '/home/lains/.local/share/flatpak/app/com.discordapp.Discord': Too many open files
** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have group “Context”
** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have key “filesystems” in group “Context”
** (io.elementary.switchboard:10350): WARNING **: 11:35:40.010: App.vala:200: Key file does not have key “devices” in group “Context”
(...)
#1 0x00007ffff7c5126c in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2 0x00007ffff7c53378 in g_object_new_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3 0x00007ffff7c536cd in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4 0x00007fffd7a89532 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#5 0x00007ffff7e9a0eb in g_ptr_array_foreach ()
(...)
#929 0x00007ffff7c5126c in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#930 0x00007ffff7c53378 in g_object_new_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#931 0x00007ffff7c536cd in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#932 0x00007fffd7a89532 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#933 0x00007ffff7e9a0eb in g_ptr_array_foreach ()
```

**Comment by lainsce** [comment]
Here's a lengthy log post...

```bash
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from io.elementary.switchboard...
(No debugging symbols found in io.elementary.switchboard)
(gdb) run
Starting program: /usr/bin/io.elementary.switchboard 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5db6700 (LWP 10227)]
[New Thread 0x7ffff52d2700 (LWP 10228)]
[New Thread 0x7fffed1c7700 (LWP 10230)]
[New Thread 0x7fffe653e700 (LWP 10231)]
[New Thread 0x7fffd719e700 (LWP 10241)]
[New Thread 0x7fffd699d700 (LWP 10242)]
[Thread 0x7fffd699d700 (LWP 10242) exited]

** (io.elementary.switchboard:10223): CRITICAL **: 15:31:07.837: AppManager.vala:63: Unable to get installed flatpaks: Error opening directory '/home/lains/.local/share/flatpak/app/com.discordapp.Discord': Too many open files

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.837: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.837: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.837: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.837: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.918: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.918: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:07.974: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.030: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.030: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.030: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.086: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.086: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.086: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.142: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.142: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.142: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.142: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.197: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.197: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.253: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.309: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.309: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.309: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.365: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.365: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.365: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.410: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.410: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.410: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.410: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.465: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.466: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.522: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.567: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.567: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.568: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.612: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.612: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.612: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.657: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.657: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.657: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.657: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.702: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.702: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.746: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.791: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.791: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.791: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.836: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.836: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.836: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.892: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.892: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.892: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.892: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.936: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.937: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:08.992: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.048: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.048: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.048: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.104: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.104: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.104: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.160: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.160: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.160: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.161: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.216: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.216: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.261: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.306: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.306: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.306: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.417: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.417: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.417: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.551: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.551: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.551: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.551: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.662: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.662: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.785: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.863: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.863: App.vala:200: Key file does not have key “filesystems” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.863: App.vala:200: Key file does not have key “devices” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.907: App.vala:200: Key file does not have group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.908: App.vala:200: Key file does not have key “features” in group “Context”

** (io.elementary.switchboard:10223): WARNING **: 15:31:09.908: App.vala:200: Key file does not have key “filesystems” in group “Context”
^C
Thread 1 "io.elementary.s" received signal SIGINT, Interrupt.
0x00007ffff71d119b in fsync (fd=995) at ../sysdeps/unix/sysv/linux/fsync.c:27
27	../sysdeps/unix/sysv/linux/fsync.c: No such file or directory.
(gdb) bt
#0  0x00007ffff71d119b in fsync (fd=995) at ../sysdeps/unix/sysv/linux/fsync.c:27
#1  0x00007ffff7eb492e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7eb4a1a in g_file_set_contents ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7ec48e4 in g_key_file_save_to_file ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffd7a88314 in permissions_backend_app_save_overrides ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#5  0x00007fffd7a88de4 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#6  0x00007ffff7c5126c in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7c53378 in g_object_new_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7c536cd in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007fffd7a89532 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#10 0x00007ffff7e9a0eb in g_ptr_array_foreach ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fffd7a8946a in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
#12 0x00007fffd7a89ab1 in  ()
    at /usr/lib/x86_64-linux-gnu/switchboard/personal/libapplications.so
--Type <RET> for more, q to quit, c to continue without paging--Quit
(gdb) quit
A debugging session is active.

	Inferior 1 [process 10223] will be killed.

Quit anyway? (y or n) y
```

**Comment by danrabbit** [comment]
Cheers, that helps

**Comment by lainsce** [comment]
Fixed, thanks!

**Comment by lainsce** [comment]
Not yet...
